In [5]:
import torch
import numpy as np

# Initialize a Tensor

In [6]:
# directly from data
data = [[0,1], [2,3]]
x_data = torch.tensor(data)

In [9]:
# from numpy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [11]:
# create a new tensor with properties (shape and dtype) of another tensor, unless explicitly overridden
x_ones = torch.ones_like(x_data)
print(x_ones)
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.8891, 0.1015],
        [0.3307, 0.6467]])


In [12]:
# shape: tensor dimensions
shape = (2,3,)

#create tensors with random var, ones, or zeros
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.7384, 0.4311, 0.2111],
        [0.3980, 0.3342, 0.2819]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [13]:
print(f"Shape of tensor: {rand_tensor.shape}")
print(f"Datatype of tensor: {rand_tensor.dtype}")
print(f"Device tensor is stored on: {rand_tensor.device}")

Shape of tensor: torch.Size([2, 3])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [15]:
# move tensor to GPU if available
if torch.cuda.is_available():
    tensor = rand_tensor.to('cuda')
    print(f"Tensor moved to GPU: {tensor}")

# Tensor Operations

In [18]:
tensor = torch.ones(4,5)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
# modify tensor so the first column is 0
tensor[:, 1] = 0
print(tensor)


First row: tensor([1., 1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1.]])


In [23]:
# contatenate tensors
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 0., 1., 1., 1.]])


In [28]:
# matrix multiplication (two approachs)
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)
print(y1)

# element-wise product (two approachs)
z1 = tensor * tensor
z2 = tensor.mul(tensor)
print(z1)

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])
tensor([[1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1.],
        [1., 0., 1., 1., 1.]])


In [29]:
# convert single-element tensor to python scalar
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

16.0 <class 'float'>


In [30]:
# in-place operations: mutates the original tensor
# example: addition
tensor.add_(5)

tensor([[6., 5., 6., 6., 6.],
        [6., 5., 6., 6., 6.],
        [6., 5., 6., 6., 6.],
        [6., 5., 6., 6., 6.]])